---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: load-test-demo
spec:
  project: default
  source:
    repoURL: "https://github.com/vino9org/vinobank-argocd.git"
    path: load-test-demo
    targetRevision: develop
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vinobank
  syncPolicy:
    syncOptions:
      - PruneLast=true

