kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - redis.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: redis-config
    files:
      - redis.conf
