---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: "redis"
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        name: redis
    spec:
      containers:
      - name: redis
        image: redis:7.0
        args: ["/config/redis.conf"]
        ports:
          - name: redis
            containerPort: 6379
        volumeMounts:
          - name: config
            mountPath: /config
          - name: redis-data
            mountPath: /data
      volumes:
        - name: config
          configMap:
            name: redis-config
            items:
            - key: redis.conf
              path: redis.conf            
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: 
            - ReadWriteOnce
        storageClassName: longhorn
        resources:
          requests:
            storage: 2Gi

---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  