apiVersion: apps/v1
kind: Deployment
metadata:
  name: corebanking-sim-j
spec:
  selector:
    matchLabels:
      app: corebanking-sim-j
  replicas: 1
  template:
    metadata:
      labels:
        app: corebanking-sim-j
    spec:
      containers:
      - name: corebanking-sim-j
        image: ghcr.io/vino9org/corebanking-sim-j:1.0.0-SNAPSHOT
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: QUARKUS_LOG_LEVEL
            value: WARN
          - name: NEW_RELIC_APP_NAME
            value: vinobank/corebanking-sim-j
          - name: NEW_RELIC_LICENSE_KEY
            valueFrom:
              secretKeyRef:
                name: newrelic-license
                key: NEW_RELIC_LICENSE_KEY
                optional: true

---
apiVersion: v1
kind: Service
metadata:
  name: corebanking-sim-j
spec:
  type: ClusterIP
  selector:
    app: corebanking-sim-j
  ports:
  - name: http
    port: 8080
